#     _____                    _                         ___      __   _
#    / ____|                  | |                       | \ \    / /  | |
#   | (___   ___ ___  _ __ ___| |__   ___   __ _ _ __ __| |\ \  / /__ | |_ ___ _ __
#    \___ \ / __/ _ \| '__/ _ \ '_ \ / _ \ / _` | '__/ _` | \ \/ / _ \| __/ _ \ '__|
#    ____) | (_| (_) | | |  __/ |_) | (_) | (_| | | | (_| |  \  / (_) | ||  __/ |
#   |_____/ \___\___/|_|  \___|_.__/ \___/ \__,_|_|  \__,_|   \/ \___/ \__\___|_|
#
vote-session-time: 30
list-size: 10