name: Build Scoreboard-Voter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types:
    - published

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
  
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Scoreboard-Voter plugin jars
        path: jars/
